Save app namespacedname in clusterConditions
open-cluster-management-io/multicloud-integrations pull request #70
Opened 2023-04-28 19:42 UTC by lennysgarage

This PR modifies the appsetreport CRD by adding a new `app` field to save the app namespaced name for each cluster. Also working on cleaning up some messages and variable names.

2023-04-28 19:43 UTC, lennysgarage commented
/hold

2023-04-28 19:54 UTC, lennysgarage commented
/unhold

2023-04-28 19:57 UTC, mikeshng requested changes

2023-04-28 19:57 UTC, mikeshng commented on pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller.go
> +			App:          appset.appset.Namespace + "/" + appset.appset.Name,
```suggestion
			App:          appset.appset.Namespace + "/" + appset.appset.Name,
```
The app is in the same namespace as appset but the name of the app is different.
As it gathers the SyncStatus and HealthStatus in the code above, you will need to store the `app`

2023-04-28 21:04 UTC, mikeshng approved these changes
Thank you for doing this @lennysgarage !

/approve

/lgtm

2023-04-28 21:11 UTC, merged

2023-04-30 18:32 UTC, xiangjingli commented
@lennysgarage  Just a reminder that another PR is needed for updating the appsetreport CRD in here 

https://github.com/open-cluster-management-io/multicloud-operators-subscription/blob/main/deploy/olm-catalog/multicluster-operators-subscription/manifests/apps.open-cluster-management.io_multiclusterapplicationsetreports.yaml